# Generated by Django 6.0.6 on 2026-07-04 19:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'parties',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('comfort_note', models.CharField(blank=True, max_length=240)),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=2, help_text='Organizer-set per-person price. Leave blank to use equal split.', max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Party Member')], default='member', max_length=16)),
                ('display_name', models.CharField(max_length=80)),
                ('dietary_notes', models.TextField(blank=True, help_text='Member-entered dietary restrictions / allergies.')),
                ('emoji', models.CharField(blank=True, default='', max_length=8)),
                ('plus_one_of', models.ForeignKey(blank=True, help_text="Set when this member is someone's plus-one.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plus_ones', to='party.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='party.party')),
            ],
            options={
                'unique_together': {('party', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('anonymous', models.BooleanField(default=False)),
                ('multiple_choice', models.BooleanField(default=False)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.membership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='party.poll')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('blast', 'Text blast'), ('suggestion', 'Suggestion'), ('photo', 'Photo')], default='blast', max_length=12)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='party.membership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.membership')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='party.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_claim', to='party.membership')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='party.room')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('kind', models.CharField(choices=[('tasks', 'Tasks'), ('packing', 'Packing list'), ('grocery', 'Grocery list')], default='tasks', max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_lists', to='party.membership')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('quantity', models.CharField(blank=True, max_length=60)),
                ('done', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.membership')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='party.tasklist')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('listing_url', models.URLField(blank=True, help_text='Airbnb / lodging link')),
                ('wifi_info', models.CharField(blank=True, max_length=200)),
                ('lock_code', models.CharField(blank=True, max_length=80)),
                ('checkout_note', models.CharField(blank=True, max_length=240)),
                ('house_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='party.party')),
            ],
        ),
        migrations.AddField(
            model_name='tasklist',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_lists', to='party.trip'),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('claimed', 'Marked as paid'), ('confirmed', 'Confirmed received')], default='claimed', max_length=12)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='settlement_proof/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_out', to='party.membership')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_in', to='party.membership')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='party.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='party.trip'),
        ),
        migrations.AddField(
            model_name='post',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='party.trip'),
        ),
        migrations.AddField(
            model_name='poll',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='party.trip'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('incurred_on', models.DateField(blank=True, null=True)),
                ('is_pre_trip', models.BooleanField(default=False)),
                ('split_method', models.CharField(choices=[('equal', 'Split equally'), ('percent', 'Split by percentage'), ('present', 'Split by nights present'), ('custom', 'Custom amounts'), ('rooms', 'Room-comfort adjusted')], default='equal', max_length=16)),
                ('split_note', models.CharField(blank=True, help_text='Plain-language description of the algorithm used (shown to members).', max_length=300)),
                ('locked', models.BooleanField(default=False, help_text='Admin locked the split in.')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to='party.membership')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='party.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audience', models.ForeignKey(blank=True, help_text="Optional: aim this at one member (e.g. 'Eden: check the grocery list').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_announcements', to='party.membership')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.membership')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='party.trip')),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('excluded', models.BooleanField(default=False)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='party.expense')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to='party.membership')),
            ],
            options={
                'unique_together': {('expense', 'member')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive', models.DateField(blank=True, null=True)),
                ('depart', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='party.membership')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='party.trip')),
            ],
            options={
                'unique_together': {('trip', 'member')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='party.membership')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='party.polloption')),
            ],
            options={
                'unique_together': {('option', 'member')},
            },
        ),
    ]
