# Generated by Django 6.0.6 on 2026-07-05 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, help_text='Leave blank for an all-day block.', null=True)),
                ('kind', models.CharField(choices=[('travel', 'Travel'), ('hike', 'Hike'), ('meal', 'Meal'), ('water', 'Water'), ('social', 'Social'), ('free', 'Free time'), ('chore', 'Chore')], default='free', max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('distance_note', models.CharField(blank=True, help_text="e.g. '4.2 mi · 900 ft gain' — shown as a small badge for hikes.", max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='party.trip')),
            ],
            options={
                'verbose_name_plural': 'itinerary activities',
                'ordering': ['date', 'order', 'time'],
            },
        ),
    ]
