# Generated by Django 6.0.6 on 2026-07-05 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_itineraryactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of tag slugs, e.g. ['food','fun']."),
        ),
        migrations.AddField(
            model_name='membership',
            name='alias',
            field=models.CharField(blank=True, help_text="Stylized nickname, e.g. 'The Quartermaster'. Shown alongside the name.", max_length=80),
        ),
        migrations.AddField(
            model_name='membership',
            name='color',
            field=models.CharField(blank=True, choices=[('#2f7d4f', 'Forest green'), ('#6b4d2e', 'Bark brown'), ('#c9a441', 'Golden'), ('#3f7fbf', 'River blue'), ('#b0533b', 'Clay red'), ('#7a5fa0', 'Dusk purple'), ('#c47a3d', 'Amber'), ('#4d8f8b', 'Moss teal'), ('#96694b', 'Timber'), ('#5d7f35', 'Fern')], default='', max_length=9),
        ),
        migrations.AddField(
            model_name='membership',
            name='icon',
            field=models.CharField(blank=True, choices=[('leaf', 'Leaf'), ('fire', 'Campfire'), ('water', 'Water drop'), ('bark', 'Bark'), ('stone', 'Stone'), ('mushroom', 'Mushroom'), ('sun', 'Sun'), ('pine', 'Pine tree'), ('acorn', 'Acorn'), ('mountain', 'Mountain'), ('flower', 'Flower'), ('tent', 'Tent'), ('lantern', 'Lantern'), ('compass', 'Compass'), ('star', 'Star')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='membership',
            name='travel_note',
            field=models.CharField(blank=True, help_text="Perceived travel plans, e.g. 'driving down Thursday night with Grant'.", max_length=300),
        ),
        migrations.AddField(
            model_name='membership',
            name='travel_note_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone on the trip'), ('mods', 'Admins & moderators'), ('admins', 'Admins only')], default='mods', max_length=10),
        ),
        migrations.AddField(
            model_name='poll',
            name='stage',
            field=models.CharField(choices=[('suggest', 'Collecting suggestions'), ('vote', 'Voting'), ('closed', 'Closed')], default='vote', max_length=8),
        ),
        migrations.AddField(
            model_name='poll',
            name='two_stage',
            field=models.BooleanField(default=False, help_text='Stage 1: everyone suggests options. Stage 2: everyone votes (not on their own).'),
        ),
        migrations.AddField(
            model_name='polloption',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='party.membership'),
        ),
        migrations.AddField(
            model_name='post',
            name='bg_color',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('#eef4e8', 'Meadow'), ('#f6ecd9', 'Sand'), ('#e8f0f4', 'Sky'), ('#f4e8ee', 'Berry'), ('#efe9df', 'Parchment')], default='', max_length=9),
        ),
        migrations.AddField(
            model_name='post',
            name='internal_path',
            field=models.CharField(blank=True, help_text="In-app link, e.g. '/info/' — rendered as a button.", max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='link_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='post',
            name='link_url',
            field=models.URLField(blank=True, help_text='Rendered as a button on the post.'),
        ),
        migrations.AddField(
            model_name='post',
            name='poll',
            field=models.OneToOneField(blank=True, help_text='Polls surface in the feed through their linked post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_post', to='party.poll'),
        ),
        migrations.AddField(
            model_name='post',
            name='suggested_by_note',
            field=models.CharField(blank=True, help_text="e.g. 'Cooper's suggestion' when someone posts on another's behalf.", max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='trip',
            name='address',
            field=models.CharField(blank=True, help_text='Full street address (copyable in-app).', max_length=240),
        ),
        migrations.AddField(
            model_name='trip',
            name='baths',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='beds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='check_in_note',
            field=models.CharField(blank=True, help_text="e.g. 'Check-in 4 PM — keypad'", max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='check_out_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='guests',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='host_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='trip',
            name='listing_summary',
            field=models.TextField(blank=True, help_text='Description copied from the listing.'),
        ),
        migrations.AddField(
            model_name='trip',
            name='listing_title',
            field=models.CharField(blank=True, help_text="e.g. 'Home in Berkeley Springs'", max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='simplify_debts',
            field=models.BooleanField(default=False, help_text='When on, the settle screen shows the minimal set of payments instead of raw pairwise tabs.'),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_method',
            field=models.CharField(choices=[('equal', 'Split equally'), ('percent', 'Split by percentages'), ('shares', 'Split by shares'), ('present', 'Split by nights present'), ('custom', 'Exact amounts'), ('rooms', 'Room-comfort adjusted')], default='equal', max_length=16),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('blast', 'Note'), ('suggestion', 'Suggestion'), ('photo', 'Photo'), ('poll', 'Poll')], default='blast', max_length=12),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='party.post')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TripPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trip_photos/')),
                ('static_path', models.CharField(blank=True, help_text="Alternative to an upload: path under static/, e.g. 'img/brock-cabin.jpg'.", max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='party.trip')),
            ],
            options={
                'ordering': ['-is_cover', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_prompt_answered', models.BooleanField(default=False)),
                ('sounds_on', models.BooleanField(default=True)),
                ('icon_prompt_done', models.BooleanField(default=False)),
                ('primary_trip', models.ForeignKey(blank=True, help_text='If set, the trips home screen is skipped until the trip ends.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='party.trip')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guiltali_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('recipe', 'Recipe'), ('note', 'Note')], default='note', max_length=8)),
                ('body', models.TextField(help_text="Plain text; blank lines split paragraphs, lines starting with '- ' become list items.")),
                ('restricted', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('allowed_members', models.ManyToManyField(blank=True, help_text='Members (besides admins/mods) who can see a restricted page.', related_name='visible_info_pages', to='party.membership')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_pages', to='party.trip')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('trip', 'slug')},
            },
        ),
    ]
