# Generated by Django 6.0.6 on 2026-07-05 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_expense_tags_membership_alias_membership_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='infopage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='party.membership'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='party.membership'),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_ai',
            field=models.BooleanField(default=False, help_text='Marks the Party AI Squire suggestion account.'),
        ),
        migrations.AddField(
            model_name='membership',
            name='nickname',
            field=models.CharField(blank=True, help_text='If set, shown big everywhere instead of the real name (real name shows tiny underneath).', max_length=60),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Whoever last checked or unchecked this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='party.membership'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='party.membership'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='party.membership'),
        ),
        migrations.AddField(
            model_name='trip',
            name='area_guide',
            field=models.TextField(blank=True, help_text="Local area guide (spas, national parks, etc). Same '- ' list formatting as InfoPage."),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='kind',
            field=models.CharField(choices=[('recipe', 'Recipe'), ('note', 'Note'), ('location', 'Location suggestions'), ('movie', 'Movie suggestions')], default='note', max_length=8),
        ),
        migrations.AlterField(
            model_name='membership',
            name='alias',
            field=models.CharField(blank=True, help_text="Stylized title, e.g. 'The Quartermaster'. Shown alongside the name.", max_length=80),
        ),
        migrations.AlterField(
            model_name='membership',
            name='display_name',
            field=models.CharField(help_text='Real first + last name.', max_length=80),
        ),
        migrations.AlterField(
            model_name='poll',
            name='closes_at',
            field=models.DateTimeField(blank=True, help_text='Defaults to 2 days after the trip ends if left blank.', null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='party.membership'),
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', 'Thumbs up'), ('👎', 'Thumbs down'), ('❤️', 'Love it'), ('😂', 'Funny'), ('🔥', 'Fire'), ('⛺', 'Camping mood')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='party.membership')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='party.post')),
            ],
            options={
                'unique_together': {('post', 'member', 'emoji')},
            },
        ),
    ]
